### ISSUE TITLE
SSH proxy should be optional

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/vpe-router#20]
If SSH credentials aren't provided, subprocess should be used. I'm imagining somewhere around https://github.com/juju-solutions/vpe-router/blob/master/lib/charms/router.py#L44 checking config for the keys, if an explicit match to the keys needed (host, user, pass) proxy request.

```
if (keys are good):
    return do_ssh()

return subprocess
```

**Comment by AdamIsrael** [comment]
This was completed with PR #24.
